name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
 build-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
    - run: npm install
    - run: npm run docs:build
  
    - name: Deploy mybells.github.io/master
      uses: peaceiris/actions-gh-pages@v2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.ALIYUN }}
        ARGS: "-rltgoDzvO --delete"
        REMOTE_HOST: "139.196.49.192"
        REMOTE_USER: "root"
        TARGET: "/www/wwwroot/acolasia/" 
